version: "2"
services:
  nginx:
    image: judge0/nginxproxy-nginx-proxy:latest-2021-04-26
    environment:
      DEFAULT_HOST: judge0.local
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    restart: always

  judge0:
    image: judge0/judge0:latest-dev
    environment:
      VIRTUAL_HOST: judge0.local
    volumes:
      - .:/api
    ports:
      - "2358:2358"
      - "3001:3001" # For ./scripts/dev/serve-docs
    privileged: true

  db:
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always

  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    environment:
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE: judge0
      POSTGRESQL_USERNAME: judge0
      POSTGRESQL_PASSWORD: YourPasswordHere1234
      PGBOUNCER_SET_DATABASE_USER: judge0
      PGBOUNCER_DATABASE: judge0
      PGBOUNCER_PORT: 6432
    restart: always

  redis:
    image: redis:6.0
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0.conf
    volumes:
      - redis-data:/data
    restart: always

  redis-sidecar:
    image: redis:6.2.6
    command: --port 6380
    volumes:
      - redis-data:/data-sidecar
    restart: always

  resque:
    image: ennexa/resque-web:latest
    entrypoint: ""
    command:
      [
        "bash",
        "-c",
        "resque-web -FL -r redis://:$$REDIS_PASSWORD@$$REDIS_HOST:$$REDIS_PORT",
      ]
    env_file: judge0.conf
    ports:
      - "5678:5678"
    restart: always

volumes:
  postgres-data:
  redis-data:
