default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["PGBOUNCER_HOST"] %>
  port: <%= ENV["PGBOUNCER_PORT"] %>
  database: <%= ENV["PGBOUNCER_DATABASE"] %>
  username: <%= ENV["PGBOUNCER_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV["RAILS_MAX_THREADS"] %>
  prepared_statements: false
  advisory_locks: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
